"""Catálogo compartido de empresas representativas de los temas de rotación."""

from __future__ import annotations

# Se usan tickers de Yahoo Finance cuando existe una cotización accesible.
# El nombre mostrado al usuario permanece independiente del ticker.
ROTATION_COMPANY_TICKERS = {
    "Apple": "AAPL", "Microsoft": "MSFT", "NVIDIA": "NVDA", "Broadcom": "AVGO",
    "Oracle": "ORCL", "TSMC": "TSM", "ASML": "ASML", "AMD": "AMD", "Intel": "INTC",
    "Qualcomm": "QCOM", "Salesforce": "CRM", "Adobe": "ADBE", "Intuit": "INTU",
    "Synopsys": "SNPS", "Vertiv": "VRT", "Meta": "META", "Amazon": "AMZN",
    "Alphabet": "GOOGL", "Cisco": "CSCO", "Ericsson": "ERIC", "Equinix": "EQIX",
    "Digital Realty": "DLR", "American Tower": "AMT", "Crown Castle": "CCI",
    "Eaton": "ETN", "ABB": "ABBNY", "Schneider": "SBGSF", "Quanta Services": "PWR",
    "Hubbell": "HUBB", "Crowdstrike": "CRWD", "Palo Alto": "PANW", "Fortinet": "FTNT",
    "Zscaler": "ZS", "Eli Lilly": "LLY", "UnitedHealth": "UNH",
    "Johnson & Johnson": "JNJ", "AbbVie": "ABBV", "Merck": "MRK", "Amgen": "AMGN",
    "Gilead": "GILD", "Moderna": "MRNA", "Biogen": "BIIB", "Regeneron": "REGN",
    "Pfizer": "PFE", "Progressive": "PGR", "Chubb": "CB", "AIG": "AIG",
    "Travelers": "TRV", "MetLife": "MET", "JPMorgan": "JPM", "Bank of America": "BAC",
    "Wells Fargo": "WFC", "Citigroup": "C", "US Bancorp": "USB", "GE": "GE",
    "Caterpillar": "CAT", "RTX": "RTX", "Honeywell": "HON", "Union Pacific": "UNP",
    "Boeing": "BA", "Lockheed Martin": "LMT", "Northrop Grumman": "NOC",
    "Tesla": "TSLA", "Home Depot": "HD", "McDonald's": "MCD", "Nike": "NKE",
    "NextEra": "NEE", "Southern": "SO", "Duke Energy": "DUK", "Constellation": "CEG",
    "American Electric": "AEP", "Linde": "LIN", "Sherwin-Williams": "SHW",
    "Freeport": "FCX", "Ecolab": "ECL", "Air Products": "APD", "Exxon": "XOM",
    "Chevron": "CVX", "ConocoPhillips": "COP", "Schlumberger": "SLB", "Toyota": "TM",
    "Sony": "SONY", "Mitsubishi UFJ": "MUFG", "SoftBank": "SFTBY", "Tencent": "TCEHY",
    "Alibaba": "BABA", "China Construction Bank": "CICHY", "Meituan": "MPNGY",
    "BYD": "BYDDY", "Samsung": "SSNLF", "SK Hynix": "000660.KS", "Hyundai": "HYMTF",
    "KB Financial": "KB", "POSCO": "PKX", "Reliance": "RLNIY",
}

# Ampliación para que cada tema tenga una cesta informativa de hasta 15
# compañías. Se muestran como universo de seguimiento, no como cartera.
ROTATION_COMPANY_TICKERS.update({
    "Netflix": "NFLX", "Texas Instruments": "TXN", "Micron": "MU", "Applied Materials": "AMAT",
    "Lam Research": "LRCX", "KLA": "KLAC", "Marvell": "MRVL", "Analog Devices": "ADI",
    "GlobalFoundries": "GFS", "NXP": "NXPI", "Cadence": "CDNS", "Arm": "ARM",
    "ServiceNow": "NOW", "Workday": "WDAY", "SAP": "SAP", "Palantir": "PLTR",
    "Autodesk": "ADSK", "Shopify": "SHOP", "HubSpot": "HUBS", "Dell": "DELL",
    "Super Micro": "SMCI", "Arista": "ANET", "Juniper": "JNPR", "Nokia": "NOK",
    "Corning": "GLW", "Ciena": "CIEN", "Motorola Solutions": "MSI", "CommScope": "COMM",
    "Lumentum": "LITE", "Iron Mountain": "IRM", "SBA Communications": "SBAC",
    "DigitalBridge": "DBRG", "CoreWeave": "CRWV", "Lamar": "LAMR", "Cloudflare": "NET",
    "GE Vernova": "GEV", "Siemens": "SIEGY", "Emerson": "EMR", "Rockwell": "ROK",
    "Fluor": "FLR", "Jacobs": "J", "PPL": "PPL", "Dominion": "D",
    "AES": "AES", "Johnson Controls": "JCI", "Daikin": "DKILF", "Lennox": "LII",
    "nVent": "NVT", "SPX Technologies": "SPXC", "AAON": "AAON", "Munters": "MTRS",
    "Snowflake": "SNOW", "Datadog": "DDOG", "MongoDB": "MDB", "IBM": "IBM", "Okta": "OKTA",
    "Akamai": "AKAM", "Gen Digital": "GEN", "Check Point": "CHKP", "CyberArk": "CYBR",
    "Tenable": "TENB", "SentinelOne": "S", "Rapid7": "RPD", "Varonis": "VRNS",
    "Rubrik": "RBRK", "Becton Dickinson": "BDX", "Medtronic": "MDT", "Stryker": "SYK",
    "Thermo Fisher": "TMO", "Danaher": "DHR", "Boston Scientific": "BSX", "HCA": "HCA",
    "CVS": "CVS", "Vertex": "VRTX", "CRISPR Therapeutics": "CRSP", "Illumina": "ILMN",
    "BioNTech": "BNTX", "Alnylam": "ALNY", "Veeva": "VEEV", "Johnson & Johnson": "JNJ",
    "Bristol Myers Squibb": "BMY", "Novo Nordisk": "NVO", "AstraZeneca": "AZN",
    "Sanofi": "SNY", "Eisai": "ESALY", "Takeda": "TAK", "Cigna": "CI",
    "Humana": "HUM", "Marsh McLennan": "MMC", "Aon": "AON", "Allstate": "ALL",
    "Hartford": "HIG", "JPMorgan": "JPM", "Goldman Sachs": "GS", "Morgan Stanley": "MS",
    "BlackRock": "BLK", "PNC": "PNC", "Charles Schwab": "SCHW", "Truist": "TFC",
    "Capital One": "COF", "GE Aerospace": "GE", "Deere": "DE", "3M": "MMM",
    "Illinois Tool Works": "ITW", "FedEx": "FDX", "C.H. Robinson": "CHRW", "Waste Management": "WM",
    "General Dynamics": "GD", "L3Harris": "LHX", "Boeing": "BA", "Textron": "TXT",
    "General Motors": "GM", "Ford": "F", "Starbucks": "SBUX", "TJX": "TJX",
    "Lowe's": "LOW", "Booking": "BKNG", "Marriott": "MAR", "AutoZone": "AZO",
    "Target": "TGT", "Costco": "COST", "Walmart": "WMT", "Procter & Gamble": "PG",
    "Duke Energy": "DUK", "Dominion Energy": "D", "Exelon": "EXC", "American Water": "AWK",
    "Vistra": "VST", "Public Service Enterprise": "PEG", "Newmont": "NEM", "Rio Tinto": "RIO",
    "Nucor": "NUE", "Corteva": "CTVA", "Dow": "DOW", "Vulcan Materials": "VMC",
    "Martin Marietta": "MLM", "Mosaic": "MOS", "Occidental": "OXY", "EOG Resources": "EOG",
    "Phillips 66": "PSX", "Marathon Petroleum": "MPC", "Halliburton": "HAL", "Baker Hughes": "BKR",
    "Honda": "HMC", "Hitachi": "HTHIY", "Nintendo": "NTDOY", "Mitsui": "MITSY",
    "Recruit": "RCRRF", "Fast Retailing": "FRCOY", "Panasonic": "PCRFY", "Canon": "CAJ",
    "Mizuho": "MFG", "Itochu": "ITOCY", "Tencent Music": "TME", "JD.com": "JD",
    "PDD": "PDD", "NetEase": "NTES", "Trip.com": "TCOM", "China Mobile": "CHL",
    "Baidu": "BIDU", "Li Auto": "LI", "XPeng": "XPEV", "NIO": "NIO",
    "SK Telecom": "SKM", "LG": "LPL", "Kia": "KIMTF", "Samsung SDI": "SSDIY",
    "Naver": "NHNCF", "Hyundai Mobis": "HYMTF", "LG Chem": "LGCLF", "Hana Financial": "HAFG",
    "Modine": "MOD", "Carrier": "CARR", "Trane": "TT", "Abbott": "ABT", "The Hartford": "HIG",
    "Parker-Hannifin": "PH", "Kratos Defense": "KTOS", "Leidos": "LDOS", "TransDigm": "TDG",
    "Curtiss-Wright": "CW", "Howmet Aerospace": "HWM", "Valero": "VLO", "Devon Energy": "DVN",
    "Kinder Morgan": "KMI", "Williams": "WMB", "ONEOK": "OKE", "Keyence": "KYCCF",
    "Celltrion": "068270.KS", "Kakao": "KAKAF", "Edison International": "EIX", "Xcel Energy": "XEL",
    "Sempra": "SRE", "Albemarle": "ALB", "Eastman Chemical": "EMN", "Mitsui": "MITSY",
    "Kratos": "KTOS",
    "Santander": "SAN", "BBVA": "BBVA", "Iberdrola": "IBDRY", "Inditex": "IDEXY",
    "Telefónica": "TEF", "Amadeus": "AMADY", "Repsol": "REPYY", "Ferrovial": "FER",
    "Cellnex": "CLLNY", "Aena": "ANYYY", "CaixaBank": "CAIXY", "Grifols": "GRFS",
    "Acciona": "ACXIF", "Naturgy": "GASNY", "Banco Sabadell": "BNDSY",
})


ROTATION_THEME_COMPANIES = {
    "XLK": ["Apple", "Microsoft", "NVIDIA", "Broadcom", "Oracle", "Meta", "Alphabet", "Amazon", "Tesla", "Netflix", "Adobe", "Salesforce", "AMD", "TSMC", "Qualcomm"],
    "SMH": ["NVIDIA", "TSMC", "ASML", "Broadcom", "AMD", "Intel", "Qualcomm", "Texas Instruments", "Micron", "Applied Materials", "Lam Research", "KLA", "Marvell", "Synopsys", "Cadence"],
    "SOXX": ["NVIDIA", "Broadcom", "AMD", "Intel", "Qualcomm", "Micron", "Texas Instruments", "Applied Materials", "Lam Research", "KLA", "ASML", "Marvell", "Analog Devices", "GlobalFoundries", "NXP"],
    "IGV": ["Microsoft", "Salesforce", "Adobe", "Intuit", "Synopsys", "Oracle", "ServiceNow", "Workday", "SAP", "Palantir", "Crowdstrike", "Palo Alto", "Autodesk", "Shopify", "HubSpot"],
    "AIQ": ["NVIDIA", "Microsoft", "Meta", "Amazon", "Alphabet", "Broadcom", "AMD", "Oracle", "Palantir", "Salesforce", "ServiceNow", "Arista", "Vertiv", "Super Micro", "Dell"],
    "FIVG": ["Apple", "Cisco", "Qualcomm", "Broadcom", "Ericsson", "Arista", "Marvell", "Juniper", "Nokia", "Corning", "Ciena", "Motorola Solutions", "CommScope", "Lumentum", "Dell"],
    "SRVR": ["Equinix", "Digital Realty", "American Tower", "Crown Castle", "Iron Mountain", "SBA Communications", "DigitalBridge", "CoreWeave", "Lamar", "Amazon", "Microsoft", "Alphabet", "Oracle", "Vertiv", "Cisco"],
    "GRID": ["Eaton", "ABB", "Schneider", "Quanta Services", "Hubbell", "GE Vernova", "Siemens", "Emerson", "Rockwell", "Fluor", "Jacobs", "PPL", "Dominion", "AES", "Duke Energy"],
    "VRT": ["Vertiv", "Modine", "Carrier", "Trane", "Eaton", "Johnson Controls", "Schneider", "Daikin", "Lennox", "Honeywell", "nVent", "SPX Technologies", "AAON", "Munters", "Emerson"],
    "SKYY": ["Amazon", "Microsoft", "Oracle", "Salesforce", "ServiceNow", "Alphabet", "Snowflake", "Datadog", "Cloudflare", "MongoDB", "Workday", "SAP", "IBM", "Akamai", "Cisco"],
    "CIBR": ["Crowdstrike", "Palo Alto", "Fortinet", "Zscaler", "Check Point", "Okta", "Cloudflare", "CyberArk", "Tenable", "SentinelOne", "Rapid7", "Varonis", "Akamai", "Gen Digital", "Rubrik"],
    "XLV": ["Eli Lilly", "UnitedHealth", "Johnson & Johnson", "AbbVie", "Merck", "Pfizer", "Abbott", "Becton Dickinson", "Medtronic", "Stryker", "Thermo Fisher", "Danaher", "Boston Scientific", "HCA", "CVS"],
    "XBI": ["Amgen", "Gilead", "Moderna", "Biogen", "Regeneron", "Vertex", "CRISPR Therapeutics", "Illumina", "BioNTech", "Alnylam", "AbbVie", "Eli Lilly", "Pfizer", "Danaher", "Thermo Fisher"],
    "PJP": ["Eli Lilly", "Johnson & Johnson", "Pfizer", "Merck", "AbbVie", "Bristol Myers Squibb", "Amgen", "Gilead", "Novo Nordisk", "AstraZeneca", "Sanofi", "Regeneron", "Takeda", "Eisai", "Vertex"],
    "KIE": ["Progressive", "Chubb", "AIG", "Travelers", "MetLife", "UnitedHealth", "Cigna", "Humana", "Marsh McLennan", "Aon", "Allstate", "Hartford", "BlackRock", "JPMorgan", "The Hartford"],
    "KBE": ["JPMorgan", "Bank of America", "Wells Fargo", "Citigroup", "US Bancorp", "Goldman Sachs", "Morgan Stanley", "BlackRock", "PNC", "Charles Schwab", "Truist", "Capital One", "Mizuho", "Mitsubishi UFJ", "KB Financial"],
    "XLI": ["GE", "Caterpillar", "RTX", "Honeywell", "Union Pacific", "Deere", "3M", "Illinois Tool Works", "FedEx", "C.H. Robinson", "Waste Management", "Emerson", "Rockwell", "Parker-Hannifin", "Quanta Services"],
    "ITA": ["GE", "RTX", "Boeing", "Lockheed Martin", "Northrop Grumman", "General Dynamics", "L3Harris", "Honeywell", "Textron", "Caterpillar", "Kratos Defense", "Leidos", "TransDigm", "Curtiss-Wright", "Howmet Aerospace"],
    "XLY": ["Amazon", "Tesla", "Home Depot", "McDonald's", "Nike", "General Motors", "Ford", "Starbucks", "TJX", "Lowe's", "Booking", "Marriott", "AutoZone", "Target", "Costco"],
    "XLU": ["NextEra", "Southern", "Duke Energy", "Constellation", "American Electric", "Dominion Energy", "Exelon", "American Water", "Vistra", "PPL", "Public Service Enterprise", "AES", "Edison International", "Xcel Energy", "Sempra"],
    "XLB": ["Linde", "Sherwin-Williams", "Freeport", "Ecolab", "Air Products", "Newmont", "Rio Tinto", "Nucor", "Corteva", "Dow", "Vulcan Materials", "Martin Marietta", "Mosaic", "Albemarle", "Eastman Chemical"],
    "XLE": ["Exxon", "Chevron", "ConocoPhillips", "EOG Resources", "Schlumberger", "Occidental", "Phillips 66", "Marathon Petroleum", "Halliburton", "Baker Hughes", "Valero", "Devon Energy", "Kinder Morgan", "Williams", "ONEOK"],
    "EWJ": ["Toyota", "Sony", "Mitsubishi UFJ", "Keyence", "SoftBank", "Honda", "Hitachi", "Nintendo", "Mitsui", "Recruit", "Fast Retailing", "Panasonic", "Canon", "Mizuho", "Itochu"],
    "FXI": ["Tencent", "Alibaba", "China Construction Bank", "Meituan", "BYD", "JD.com", "PDD", "NetEase", "Trip.com", "Baidu", "China Mobile", "Li Auto", "XPeng", "NIO", "Tencent Music"],
    "AAXJ": ["TSMC", "Tencent", "Samsung", "Alibaba", "Reliance", "SK Hynix", "Sony", "JD.com", "PDD", "NetEase", "Naver", "Toyota", "BYD", "Baidu", "LG"],
    "EWY": ["Samsung", "SK Hynix", "Hyundai", "KB Financial", "POSCO", "LG", "Kia", "Samsung SDI", "Naver", "Hyundai Mobis", "LG Chem", "Hana Financial", "SK Telecom", "Celltrion", "Kakao"],
    "EWP": ["Santander", "BBVA", "Iberdrola", "Inditex", "Telefónica", "Amadeus", "Repsol", "Ferrovial", "Cellnex", "Aena", "CaixaBank", "Grifols", "Acciona", "Naturgy", "Banco Sabadell"],
}
